### ISSUE TITLE
Calculation box changing size

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-decimals#6]
The width of the partially hidden Area Model Calculation box (The middle option) changes when dragging the partitions.  While the max width is changeable to allow for very large calculations, similar uses in the Area Model suite, or even the fully visible Area Model Calculation option, seem to have the width set at the width of the graph.
Found while working on https://github.com/phetsims/QA/issues/201, but unrelated as it appears in Win 10 as well.
Steps to reproduce:
1. Go to Area Model Decimals
2. Go to the 2x2 or 3x3 scene
3. Drag the area so it is larger than 1x1
4. Select the partially hidden Area Model Calculation box
5. Drag a partition back and forth, making sure it crosses a spot where one of the partitions = 1.

Example on partially hidden box:
![twitching](https://user-images.githubusercontent.com/41024075/46620689-a2f22d00-cae2-11e8-8afd-79d6c99f74cb.gif)
Example on fully visible box:
![notwitching](https://user-images.githubusercontent.com/41024075/46620708-aeddef00-cae2-11e8-990a-f0ac83346dd9.gif)

**Comment by jonathanolson** [comment]
Hmm, the reason this happens is because the line-by-line view mode requires extra arrow buttons (with currently extra padding):

![area-expanded-box](https://user-images.githubusercontent.com/480878/47402174-7d2f6f80-d701-11e8-96a0-b9bcf5915c92.PNG)

This could be potentially solved by:

1. Adjusting spacing/sizes so that this line will fit without expanding the box.
2. It looks like the arrows are always either above or below where any calculation lines would be. So instead of shifting the arrows so they will be to the right of the calculation lines, instead they could just be above/below the calculation lines. Then no extra padding would be required for that mode.
3. Expanding the "minimum" size of the box to include this extra size. It then wouldn't line up as nicely with the area above.

Thoughts on ideally 1 or 2?

**Comment by amanda-phet** [comment]
I like either 2 or 3, so let's try 2 :) 

So, in the cases that push the box to be wider, the box would instead stay the same width but the longest calculation line would simply run between the arrows a bit?

**Comment by jonathanolson** [comment]
> So, in the cases that push the box to be wider, the box would instead stay the same width but the longest calculation line would simply run between the arrows a bit?

Correct. Implemented above, so for example for decimals it doesn't cause a panel expansion:

<img width="439" alt="screen shot 2018-11-06 at 11 16 10 am" src="https://user-images.githubusercontent.com/480878/48084630-7b5fb480-e1b5-11e8-886f-3cc34de5eea8.png">

but for cases like in the variables screen that require expansion anyways:

<img width="514" alt="screen shot 2018-11-06 at 11 16 20 am" src="https://user-images.githubusercontent.com/480878/48084657-8ca8c100-e1b5-11e8-9684-584f3b7d1124.png">

Does this look acceptable to you?

**Comment by amanda-phet** [comment]
Eh, I've been sitting on this for a while and I think having the text spill into the scroll bar looks sloppy. Especially since - if I remember correctly- we were planning to treat that scroll bar as a "slider" for keyboard nav so you could easily press up/down instead of tabbing between two buttons. 

I'd rather leave it as it is than make this change... but am still open to discussing it. I can't be conclusive at the moment but wanted to be sure to respond.

**Comment by amanda-phet** [comment]
![image](https://user-images.githubusercontent.com/7852916/48156915-969cf380-e28b-11e8-9a6b-6080c8c7ad3c.png)

**Comment by jonathanolson** [comment]
Understood! The change was committed to master, but I can easily revert if it's not desired.

**Comment by amanda-phet** [comment]
@jonathanolson and I discussed this and decided to go with option 3. There are tradeoffs of course, but other considerations make it seem the most worthwhile.

**Comment by jonathanolson** [comment]
Implemented. Can you check master to see if it looks good?

**Comment by KatieWoe** [comment]
Looks good in my opinion.  Just checked the situation described in the initial issue though.

**Comment by amanda-phet** [comment]
Looks good to me. Thanks @jonathanolson

**Comment by jonathanolson** [comment]
Sounds good, I'll ask about whether things are stable enough for branching at tomorrow's dev meeting.
